require: rubocop-rails

#Cop files_to_ignore
AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - 'temp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - db/migrate/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: false
